<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZA-5CD350K5XK" failures="1" tests="11" name="tests.RegistrationPageTest" time="355.021" errors="0" timestamp="2024-08-18T20:04:22 SAST" skipped="0">
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="29.372"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="32.142"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="35.895"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="28.431"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="27.924"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="29.140"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="54.502">
    <failure message="OTP not sent. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: OTP not sent. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.RegistrationPageTest.verifyRegistration(RegistrationPageTest.java:98)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- verifyRegistration -->
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="28.369"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="29.804"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="28.310"/>
  <testcase classname="tests.RegistrationPageTest" name="verifyRegistration" time="31.132"/>
</testsuite> <!-- tests.RegistrationPageTest -->
